# -*- coding: utf-8 -*-
"""DS_C4SC4_RUB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYdhrSjGP7JmYTUz-m74IfVkO5WzUFRT
"""

import streamlit as st
import pandas as pd
import datetime
from PIL import Image

data = pd.read_csv("Employee_data.csv")

columnas_seleccionadas = [
    'name_employee',
    'birth_date',
    'age',
    'gender',
    'marital_status',
    'hiring_date',
    'position',
    'salary',
    'performance_score',
    'last_performance_date',
    'average_work_hours',
    'satisfaction_level',
    'absences'
]

data = data[columnas_seleccionadas].copy()

st.title("📊 Panel de Análisis de Empleados")

st.markdown("""
Bienvenido a la aplicación web de gestión de talento. Este sistema permite analizar de
manera detallada la base de datos de los colaboradores de la empresa, mostrando
indicadores clave como el rendimiento, niveles de satisfacción, salarios y ausentismo
para facilitar la toma de decisiones estratégicas en Recursos Humanos.
""")

image = Image.open(‘logotipo.jpg’)
st.image(image, caption=’Logotipo de la compañia’) 
